In [2]:
# linear кластер ds intro 2022
import pandas as pd
import numpy as np
import pylab
from matplotlib import pyplot as plt
%matplotlib inline
import seaborn as sns
from sklearn.preprocessing import StandardScaler
%config InlineBackend.figure_format = 'retina'
from pylab import rcParams
from sklearn.cluster import KMeans, AgglomerativeClustering, DBSCAN, AffinityPropagation
rcParams['figure.figsize'] = (16, 12)
data = pd.read_excel("geo.xlsx")

In [1]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.0.10-py2.py3-none-any.whl (242 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 242.1/242.1 kB 495.3 kB/s eta 0:00:00a 0:00:01
Collecting et-xmlfile
  Downloading et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.0.10

In [5]:
data

        Unnamed: 0          x          y  comment_class
0                0  37.612416  55.777454             -1
1                1  37.612416  55.777454             -1
2                2  37.603298  55.742108             -1
3                3  37.558526  55.728758             -1
4                4  37.566431  55.731794             -1
...            ...        ...        ...            ...
108801      108801  37.454528  55.792331             -1
108802      108802  37.384325  55.899068             -1
108803      108803  37.421066  55.848756              1
108804      108804  37.448509  55.793065             -1
108805      108805  37.451249  55.836620             -1

[108806 rows x 4 columns]